services:
  - type: web
    name: grand-majlis-bot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
